### ISSUE TITLE
Add lower resolution cover image (urls)

### ISSUE THREAD

**Issue by valflrt** [Geoxor/geoxor.moe#25]
lower resolution cover images (urls) could be added in [.../assets/covers/](https://github.com/Geoxor/geoxor.moe/tree/master/src/assets/covers) so people with a poor internet connection (I am one of them btw TvT) don't see the covers in the homepage loading.
example:
```json
{
  "name": "Ephemeral",
  "original": "https://cdn.discordapp.com/attachments/550913067517607946/860219898332446760/cover.png",
  "128px": "https://cdn.discordapp.com/attachments/550913067517607946/860219898332446760/cover128.png",
  "256px": "https://cdn.discordapp.com/attachments/550913067517607946/860219898332446760/cover256.png"
}
```

[This site](https://www.reduceimages.com/) could be useful to resize the cover images

**Comment by Geoxor** [comment]
this issue is already dealt with on the new website https://beta.geoxor.moe which this repository is about, i think you're refereing to the old site https://geoxor.moe

**Comment by valflrt** [comment]
@Geoxor I am sorry I didn't see that image size was specified in the discord url
