### ISSUE TITLE
Mark EP songs as such (instead of as Singles)

### ISSUE THREAD

**Issue by SkyyySi** [Geoxor/geoxor.moe#26]
I guess this was done because you plan to also offer to download entire EPs at once, but I think it makes sense to also mark individual songs on an EP like this, the reason being that, while the songs themselves may be seen singles, the release type is an EP.
A basic mockup:
![1](https://user-images.githubusercontent.com/53921371/157748099-5dac3528-5423-4d2a-897c-c367223be62b.png)

In addition, if you do implement "bundle downloads", I recommend showing only the EP and a button to download it (as a ZIP or something), but allow expanding them by pressing an arrow icon on the side, revealing each song (maybe with a slight indentation on the left) and individual downloads.

**Comment by Lucaskyy** [comment]
About the "download as ZIP", you can easily make a ZIP in-memory in the browser and then provide that to the end-user using blob URLs. I've done this myself in the past using [jszip](https://www.npmjs.com/package/jszip) in the browser.
So really, all you need to do then is fetch all of the songs, get the data buffer and pass that into `jszip`, get a blob out of that, and give it to the end-user.

For example, this way you can also easily add a feature to select multiple songs and download all of them in a single ZIP.
