### ISSUE TITLE
Is it allowed to make a mirror of the site?

### ISSUE THREAD

**Issue by Nofated095** [Geoxor/geoxor.moe#33]
As the title, i'm not sure if it is allowed to make a mirror of `geoxor.moe` and the assets of the site(include the musics, covers). The `geoxor.moe` is using the `cdn.discordapp.com` as the cdn. But in China, `cdn.discordapp.com` has been banned. People in China can visit `geoxor.moe` but can't see anything about the songs and can't download anything. If it is allowed to make the mirror of the site, people in China can visit the mirror and download the musics freely.
BTW, the site and assets are still under the LICENSE.

**Comment by Geoxor** [comment]
shouldnt be a problem anymore, no longer using discord
