### ISSUE TITLE
Covers and song shared using Discord are no longer working

### ISSUE THREAD

**Issue by tapnisu** [Geoxor/geoxor.moe#37]
Covers and song shipped using Discord are no longer working (due to Discord making file links expire after a day)

![image](https://github.com/Geoxor/geoxor.moe/assets/57483029/f424374d-db8a-4481-bf0d-59a723261b16)
![image](https://github.com/Geoxor/geoxor.moe/assets/57483029/86b7e5fa-808c-4a7f-a0f0-cfd2c639cfc6)

**Comment by Geoxor** [comment]
treason fixed it^
