### ISSUE TITLE
404 error in routes when reloading the page

### ISSUE THREAD

**Issue by Elder-Meyer** [Geoxor/geoxor.moe#40]
I was checking some routes in the web, like this: **https://beta.geoxor.moe/downloads/songs**

![image](https://github.com/Geoxor/geoxor.moe/assets/115410699/b944aaf7-7bfa-4939-98d5-6c3750ae6287)

and i noticed that when i reload the page the browse return with the following "404 error", also when you try enter directly to **https://beta.geoxor.moe/downloads/songs**

![image](https://github.com/Geoxor/geoxor.moe/assets/115410699/0f3b1489-8f93-42b8-accb-7a7a3fcca090)

i think this can be solved with a file in the root of the project, with config of vercel in a **vercel.json** file with the following code:

`{
    "rewrites": [
        { 
            "source": "/(.*)", "destination": "/" 
        }
    ]
}`

but idk, i have an old project where this works, to clarify this "old project" is made with **React js (jsx)** via **npm**, idk if this can change in comparision with **vue** and **yarn**

**Comment by Geoxor** [comment]
thanks for helping it seems to have worked
